// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain.config;

<<<<<<< HEAD
import edu.rit.asksg.domain.AsksgUser;
import edu.rit.asksg.domain.Person;
=======
import edu.rit.asksg.domain.config.SpringSocialConfig;
>>>>>>> origin/master

privileged aspect SpringSocialConfig_Roo_JavaBean {
    
    public String SpringSocialConfig.getHandle() {
        return this.handle;
    }
    
    public void SpringSocialConfig.setHandle(String handle) {
        this.handle = handle;
    }
    
    public String SpringSocialConfig.getUrl() {
        return this.url;
    }
    
    public void SpringSocialConfig.setUrl(String url) {
        this.url = url;
    }
    
}
