// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain.config;

<<<<<<< HEAD
=======
import edu.rit.asksg.domain.config.TwilioConfig;
>>>>>>> origin/master
import javax.persistence.Entity;

privileged aspect TwilioConfig_Roo_Jpa_Entity {
    
    declare @type: TwilioConfig: @Entity;
    
}
