// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.repository;

import org.springframework.stereotype.Repository;

privileged aspect ConversationRepository_Roo_Jpa_Repository {

    declare parents:ConversationRepository extends JpaRepository<Conversation,Long>;

    declare parents:ConversationRepository extends JpaSpecificationExecutor<Conversation>;

    declare @type: ConversationRepository:@Repository;

}
