// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.Conversation;
import edu.rit.asksg.domain.Message;
import edu.rit.asksg.domain.Service;
import java.util.List;
import org.joda.time.LocalDateTime;

privileged aspect Conversation_Roo_JavaBean {
    
    public List<Message> Conversation.getMessages() {
        return this.messages;
    }
    
    public void Conversation.setMessages(List<Message> messages) {
        this.messages = messages;
    }
    
    public LocalDateTime Conversation.getCreated() {
        return this.created;
    }
    
    public void Conversation.setCreated(LocalDateTime created) {
        this.created = created;
    }
    
    public LocalDateTime Conversation.getModified() {
        return this.modified;
    }
    
    public void Conversation.setModified(LocalDateTime modified) {
        this.modified = modified;
    }
    
    public Service Conversation.getService() {
        return this.service;
    }
    
    public void Conversation.setService(Service service) {
        this.service = service;
    }
    
    public String Conversation.getExternalId() {
        return this.externalId;
    }
    
    public void Conversation.setExternalId(String externalId) {
        this.externalId = externalId;
    }
    
    public Boolean Conversation.getHidden() {
        return this.hidden;
    }
    
    public void Conversation.setHidden(Boolean hidden) {
        this.hidden = hidden;
    }
    
    public Boolean Conversation.getIsRead() {
        return this.isRead;
    }
    
    public void Conversation.setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }
    
    public String Conversation.getSubject() {
        return this.subject;
    }
    
    public void Conversation.setSubject(String subject) {
        this.subject = subject;
    }
    
    public Boolean Conversation.getPrivateConversation() {
        return this.privateConversation;
    }
    
    public void Conversation.setPrivateConversation(Boolean privateConversation) {
        this.privateConversation = privateConversation;
    }
    
}
