// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.Conversation;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Conversation_Roo_Json {
    
    public static Conversation Conversation.fromJsonToConversation(String json) {
        return new JSONDeserializer<Conversation>().use(null, Conversation.class).deserialize(json);
    }
    
    public static String Conversation.toJsonArray(Collection<Conversation> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Conversation> Conversation.fromJsonArrayToConversations(String json) {
        return new JSONDeserializer<List<Conversation>>().use(null, ArrayList.class).use("values", Conversation.class).deserialize(json);
    }
    
}
