// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.Conversation;
import edu.rit.asksg.domain.Message;
import edu.rit.asksg.domain.Service;
import java.util.Set;
import org.joda.time.LocalDateTime;

privileged aspect Conversation_Roo_JavaBean {
    
    public Set<Message> Conversation.getMessages() {
        return this.messages;
    }
    
    public void Conversation.setMessages(Set<Message> messages) {
        this.messages = messages;
    }
    
    public LocalDateTime Conversation.getCreated() {
        return this.created;
    }
    
    public void Conversation.setCreated(LocalDateTime created) {
        this.created = created;
    }
    
    public LocalDateTime Conversation.getModified() {
        return this.modified;
    }
    
    public void Conversation.setModified(LocalDateTime modified) {
        this.modified = modified;
    }
    
    public Service Conversation.getService() {
        return this.service;
    }
    
    public void Conversation.setService(Service service) {
        this.service = service;
    }
    
    public boolean Conversation.isRead() {
        return this.read;
    }
    
    public void Conversation.setRead(boolean read) {
        this.read = read;
    }
    
    public boolean Conversation.isHidden() {
        return this.hidden;
    }
    
    public void Conversation.setHidden(boolean hidden) {
        this.hidden = hidden;
    }
    
}
