// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.Identity;

privileged aspect Identity_Roo_JavaBean {
    
    public boolean Identity.isEnabled() {
        return this.enabled;
    }
    
    public void Identity.setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    
}
