// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.Service;

privileged aspect Service_Roo_JavaBean {
    
    public String Service.getIdentifier() {
        return this.identifier;
    }
    
    public void Service.setIdentifier(String identifier) {
        this.identifier = identifier;
    }
    
}
