// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.Twilio;
import javax.persistence.Entity;

privileged aspect Twilio_Roo_Jpa_Entity {
    
    declare @type: Twilio: @Entity;
    
}
