// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import javax.persistence.Entity;

privileged aspect Twitter_Roo_Jpa_Entity {

    declare @type: Twitter:@Entity;

}
