// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.UserRole;

privileged aspect UserRole_Roo_JavaBean {
    
    public String UserRole.getName() {
        return this.name;
    }
    
    public void UserRole.setName(String name) {
        this.name = name;
    }
    
}
