// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.analytics.domain;

import edu.rit.asksg.analytics.domain.Topic;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Topic_Roo_Configurable {
    
    declare @type: Topic: @Configurable;
    
}
