// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.Conversation;
import edu.rit.asksg.domain.ConversationDataOnDemand;
import edu.rit.asksg.domain.Service;
import edu.rit.asksg.repository.ConversationRepository;
import edu.rit.asksg.service.ConversationService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ConversationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ConversationDataOnDemand: @Component;
    
    private Random ConversationDataOnDemand.rnd = new SecureRandom();
    
    private List<Conversation> ConversationDataOnDemand.data;
    
    @Autowired
    ConversationService ConversationDataOnDemand.conversationService;
    
    @Autowired
    ConversationRepository ConversationDataOnDemand.conversationRepository;
    
    public Conversation ConversationDataOnDemand.getNewTransientConversation(int index) {
        Conversation obj = new Conversation();
        setCreated(obj, index);
        setModified(obj, index);
        setProvider(obj, index);
        return obj;
    }
    
    public void ConversationDataOnDemand.setProvider(Conversation obj, int index) {
        Service provider = null;
        obj.setProvider(provider);
    }
    
    public Conversation ConversationDataOnDemand.getSpecificConversation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Conversation obj = data.get(index);
        Long id = obj.getId();
        return conversationService.findConversation(id);
    }
    
    public Conversation ConversationDataOnDemand.getRandomConversation() {
        init();
        Conversation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return conversationService.findConversation(id);
    }
    
    public boolean ConversationDataOnDemand.modifyConversation(Conversation obj) {
        return false;
    }
    
    public void ConversationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = conversationService.findConversationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Conversation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Conversation>();
        for (int i = 0; i < 10; i++) {
            Conversation obj = getNewTransientConversation(i);
            try {
                conversationService.saveConversation(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            conversationRepository.flush();
            data.add(obj);
        }
    }
    
}
