// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.ConversationDataOnDemand;
import edu.rit.asksg.domain.ConversationIntegrationTest;
import edu.rit.asksg.repository.ConversationRepository;
import edu.rit.asksg.service.ConversationService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConversationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConversationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConversationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConversationIntegrationTest: @Transactional;
    
    @Autowired
    ConversationDataOnDemand ConversationIntegrationTest.dod;
    
    @Autowired
    ConversationService ConversationIntegrationTest.conversationService;
    
    @Autowired
    ConversationRepository ConversationIntegrationTest.conversationRepository;
    
    @Test
    public void ConversationIntegrationTest.testCountAllConversations() {
        Assert.assertNotNull("Data on demand for 'Conversation' failed to initialize correctly", dod.getRandomConversation());
        long count = conversationService.countAllConversations();
        Assert.assertTrue("Counter for 'Conversation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConversationIntegrationTest.testFindConversation() {
        Conversation obj = dod.getRandomConversation();
        Assert.assertNotNull("Data on demand for 'Conversation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Conversation' failed to provide an identifier", id);
        obj = conversationService.findConversation(id);
        Assert.assertNotNull("Find method for 'Conversation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Conversation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConversationIntegrationTest.testFindAllConversations() {
        Assert.assertNotNull("Data on demand for 'Conversation' failed to initialize correctly", dod.getRandomConversation());
        long count = conversationService.countAllConversations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Conversation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Conversation> result = conversationService.findAllConversations();
        Assert.assertNotNull("Find all method for 'Conversation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Conversation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConversationIntegrationTest.testFindConversationEntries() {
        Assert.assertNotNull("Data on demand for 'Conversation' failed to initialize correctly", dod.getRandomConversation());
        long count = conversationService.countAllConversations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Conversation> result = conversationService.findConversationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Conversation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Conversation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConversationIntegrationTest.testFlush() {
        Conversation obj = dod.getRandomConversation();
        Assert.assertNotNull("Data on demand for 'Conversation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Conversation' failed to provide an identifier", id);
        obj = conversationService.findConversation(id);
        Assert.assertNotNull("Find method for 'Conversation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConversation(obj);
        Integer currentVersion = obj.getVersion();
        conversationRepository.flush();
        Assert.assertTrue("Version for 'Conversation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConversationIntegrationTest.testUpdateConversationUpdate() {
        Conversation obj = dod.getRandomConversation();
        Assert.assertNotNull("Data on demand for 'Conversation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Conversation' failed to provide an identifier", id);
        obj = conversationService.findConversation(id);
        boolean modified =  dod.modifyConversation(obj);
        Integer currentVersion = obj.getVersion();
        Conversation merged = conversationService.updateConversation(obj);
        conversationRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Conversation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConversationIntegrationTest.testSaveConversation() {
        Assert.assertNotNull("Data on demand for 'Conversation' failed to initialize correctly", dod.getRandomConversation());
        Conversation obj = dod.getNewTransientConversation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Conversation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Conversation' identifier to be null", obj.getId());
        conversationService.saveConversation(obj);
        conversationRepository.flush();
        Assert.assertNotNull("Expected 'Conversation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConversationIntegrationTest.testDeleteConversation() {
        Conversation obj = dod.getRandomConversation();
        Assert.assertNotNull("Data on demand for 'Conversation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Conversation' failed to provide an identifier", id);
        obj = conversationService.findConversation(id);
        conversationService.deleteConversation(obj);
        conversationRepository.flush();
        Assert.assertNull("Failed to remove 'Conversation' with identifier '" + id + "'", conversationService.findConversation(id));
    }
    
}
