// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.MessageDataOnDemand;
import edu.rit.asksg.domain.MessageIntegrationTest;
import edu.rit.asksg.repository.MessageRepository;
import edu.rit.asksg.service.MessageService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MessageIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MessageIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MessageIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MessageIntegrationTest: @Transactional;
    
    @Autowired
    MessageDataOnDemand MessageIntegrationTest.dod;
    
    @Autowired
    MessageService MessageIntegrationTest.messageService;
    
    @Autowired
    MessageRepository MessageIntegrationTest.messageRepository;
    
    @Test
    public void MessageIntegrationTest.testCountAllMessages() {
        Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", dod.getRandomMessage());
        long count = messageService.countAllMessages();
        Assert.assertTrue("Counter for 'Message' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MessageIntegrationTest.testFindMessage() {
        Message obj = dod.getRandomMessage();
        Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Message' failed to provide an identifier", id);
        obj = messageService.findMessage(id);
        Assert.assertNotNull("Find method for 'Message' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Message' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MessageIntegrationTest.testFindAllMessages() {
        Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", dod.getRandomMessage());
        long count = messageService.countAllMessages();
        Assert.assertTrue("Too expensive to perform a find all test for 'Message', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Message> result = messageService.findAllMessages();
        Assert.assertNotNull("Find all method for 'Message' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Message' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MessageIntegrationTest.testFindMessageEntries() {
        Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", dod.getRandomMessage());
        long count = messageService.countAllMessages();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Message> result = messageService.findMessageEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Message' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Message' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MessageIntegrationTest.testFlush() {
        Message obj = dod.getRandomMessage();
        Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Message' failed to provide an identifier", id);
        obj = messageService.findMessage(id);
        Assert.assertNotNull("Find method for 'Message' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMessage(obj);
        Integer currentVersion = obj.getVersion();
        messageRepository.flush();
        Assert.assertTrue("Version for 'Message' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MessageIntegrationTest.testUpdateMessageUpdate() {
        Message obj = dod.getRandomMessage();
        Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Message' failed to provide an identifier", id);
        obj = messageService.findMessage(id);
        boolean modified =  dod.modifyMessage(obj);
        Integer currentVersion = obj.getVersion();
        Message merged = messageService.updateMessage(obj);
        messageRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Message' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MessageIntegrationTest.testSaveMessage() {
        Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", dod.getRandomMessage());
        Message obj = dod.getNewTransientMessage(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Message' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Message' identifier to be null", obj.getId());
        messageService.saveMessage(obj);
        messageRepository.flush();
        Assert.assertNotNull("Expected 'Message' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MessageIntegrationTest.testDeleteMessage() {
        Message obj = dod.getRandomMessage();
        Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Message' failed to provide an identifier", id);
        obj = messageService.findMessage(id);
        messageService.deleteMessage(obj);
        messageRepository.flush();
        Assert.assertNull("Failed to remove 'Message' with identifier '" + id + "'", messageService.findMessage(id));
    }
    
}
