// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.Analytics;
import edu.rit.asksg.domain.ConversationDataOnDemand;
import edu.rit.asksg.domain.Message;
import edu.rit.asksg.domain.MessageDataOnDemand;
import edu.rit.asksg.repository.MessageRepository;
import edu.rit.asksg.service.MessageService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MessageDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MessageDataOnDemand: @Component;
    
    private Random MessageDataOnDemand.rnd = new SecureRandom();
    
    private List<Message> MessageDataOnDemand.data;
    
    @Autowired
    ConversationDataOnDemand MessageDataOnDemand.conversationDataOnDemand;
    
    @Autowired
    MessageService MessageDataOnDemand.messageService;
    
    @Autowired
    MessageRepository MessageDataOnDemand.messageRepository;
    
    public Message MessageDataOnDemand.getNewTransientMessage(int index) {
        Message obj = new Message();
        setAnalytics(obj, index);
        setAuthor(obj, index);
        setContent(obj, index);
        setCreated(obj, index);
        setModified(obj, index);
        setPosted(obj, index);
        setRecipient(obj, index);
        setSnippet(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void MessageDataOnDemand.setAnalytics(Message obj, int index) {
        Analytics analytics = null;
        obj.setAnalytics(analytics);
    }
    
    public void MessageDataOnDemand.setAuthor(Message obj, int index) {
        String author = "author_" + index;
        obj.setAuthor(author);
    }
    
    public void MessageDataOnDemand.setContent(Message obj, int index) {
        String content = "content_" + index;
        obj.setContent(content);
    }
    
    public void MessageDataOnDemand.setPosted(Message obj, int index) {
        Boolean posted = Boolean.FALSE;
        obj.setPosted(posted);
    }
    
    public void MessageDataOnDemand.setRecipient(Message obj, int index) {
        String recipient = "recipient_" + index;
        obj.setRecipient(recipient);
    }
    
    public void MessageDataOnDemand.setSnippet(Message obj, int index) {
        String snippet = "snippet_" + index;
        obj.setSnippet(snippet);
    }
    
    public void MessageDataOnDemand.setUrl(Message obj, int index) {
        String url = "url_" + index;
        obj.setUrl(url);
    }
    
    public Message MessageDataOnDemand.getSpecificMessage(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Message obj = data.get(index);
        Long id = obj.getId();
        return messageService.findMessage(id);
    }
    
    public Message MessageDataOnDemand.getRandomMessage() {
        init();
        Message obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return messageService.findMessage(id);
    }
    
    public boolean MessageDataOnDemand.modifyMessage(Message obj) {
        return false;
    }
    
    public void MessageDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = messageService.findMessageEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Message' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Message>();
        for (int i = 0; i < 10; i++) {
            Message obj = getNewTransientMessage(i);
            try {
                messageService.saveMessage(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            messageRepository.flush();
            data.add(obj);
        }
    }
    
}
