// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.SocialSubscriptionDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SocialSubscriptionDataOnDemand_Roo_Configurable {
    
    declare @type: SocialSubscriptionDataOnDemand: @Configurable;
    
}
