// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.domain;

import edu.rit.asksg.domain.SocialSubscriptionDataOnDemand;
import edu.rit.asksg.domain.SocialSubscriptionIntegrationTest;
import edu.rit.asksg.repository.SocialSubscriptionRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SocialSubscriptionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SocialSubscriptionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SocialSubscriptionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SocialSubscriptionIntegrationTest: @Transactional;
    
    @Autowired
    SocialSubscriptionDataOnDemand SocialSubscriptionIntegrationTest.dod;
    
    @Autowired
    SocialSubscriptionRepository SocialSubscriptionIntegrationTest.socialSubscriptionRepository;
    
    @Test
    public void SocialSubscriptionIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to initialize correctly", dod.getRandomSocialSubscription());
        long count = socialSubscriptionRepository.count();
        Assert.assertTrue("Counter for 'SocialSubscription' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SocialSubscriptionIntegrationTest.testFind() {
        SocialSubscription obj = dod.getRandomSocialSubscription();
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to provide an identifier", id);
        obj = socialSubscriptionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'SocialSubscription' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SocialSubscription' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SocialSubscriptionIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to initialize correctly", dod.getRandomSocialSubscription());
        long count = socialSubscriptionRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'SocialSubscription', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SocialSubscription> result = socialSubscriptionRepository.findAll();
        Assert.assertNotNull("Find all method for 'SocialSubscription' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SocialSubscription' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SocialSubscriptionIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to initialize correctly", dod.getRandomSocialSubscription());
        long count = socialSubscriptionRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SocialSubscription> result = socialSubscriptionRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'SocialSubscription' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SocialSubscription' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SocialSubscriptionIntegrationTest.testFlush() {
        SocialSubscription obj = dod.getRandomSocialSubscription();
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to provide an identifier", id);
        obj = socialSubscriptionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'SocialSubscription' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySocialSubscription(obj);
        Integer currentVersion = obj.getVersion();
        socialSubscriptionRepository.flush();
        Assert.assertTrue("Version for 'SocialSubscription' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SocialSubscriptionIntegrationTest.testSaveUpdate() {
        SocialSubscription obj = dod.getRandomSocialSubscription();
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to provide an identifier", id);
        obj = socialSubscriptionRepository.findOne(id);
        boolean modified =  dod.modifySocialSubscription(obj);
        Integer currentVersion = obj.getVersion();
        SocialSubscription merged = socialSubscriptionRepository.save(obj);
        socialSubscriptionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SocialSubscription' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SocialSubscriptionIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to initialize correctly", dod.getRandomSocialSubscription());
        SocialSubscription obj = dod.getNewTransientSocialSubscription(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SocialSubscription' identifier to be null", obj.getId());
        socialSubscriptionRepository.save(obj);
        socialSubscriptionRepository.flush();
        Assert.assertNotNull("Expected 'SocialSubscription' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SocialSubscriptionIntegrationTest.testDelete() {
        SocialSubscription obj = dod.getRandomSocialSubscription();
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialSubscription' failed to provide an identifier", id);
        obj = socialSubscriptionRepository.findOne(id);
        socialSubscriptionRepository.delete(obj);
        socialSubscriptionRepository.flush();
        Assert.assertNull("Failed to remove 'SocialSubscription' with identifier '" + id + "'", socialSubscriptionRepository.findOne(id));
    }
    
}
