// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.service;

import edu.rit.asksg.domain.config.ProviderConfig;
<<<<<<< HEAD

=======
import edu.rit.asksg.service.ConfigService;
>>>>>>> origin/master
import java.util.List;

privileged aspect ConfigService_Roo_Service {
    
    public abstract long ConfigService.countAllProviderConfigs();    
    public abstract void ConfigService.deleteProviderConfig(ProviderConfig providerConfig);    
    public abstract ProviderConfig ConfigService.findProviderConfig(Long id);    
    public abstract List<ProviderConfig> ConfigService.findAllProviderConfigs();    
    public abstract List<ProviderConfig> ConfigService.findProviderConfigEntries(int firstResult, int maxResults);    
    public abstract void ConfigService.saveProviderConfig(ProviderConfig providerConfig);    
    public abstract ProviderConfig ConfigService.updateProviderConfig(ProviderConfig providerConfig);    
}
