// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.service;

import edu.rit.asksg.domain.Conversation;

import java.util.List;

privileged aspect ConversationService_Roo_Service {

    public abstract long ConversationService.countAllConversations();
    public abstract void ConversationService.deleteConversation(Conversation conversation);
    public abstract Conversation ConversationService.findConversation(Long id);
    public abstract List<Conversation> ConversationService.findAllConversations();
    public abstract List<Conversation> ConversationService.findConversationEntries(int firstResult, int maxResults);
    public abstract void ConversationService.saveConversation(Conversation conversation);
    public abstract Conversation ConversationService.updateConversation(Conversation conversation);
}
