// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.rit.asksg.service;

import edu.rit.asksg.domain.Conversation;
import edu.rit.asksg.repository.ConversationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

privileged aspect ConversationServiceImpl_Roo_Service {

    declare @type: ConversationServiceImpl:@Service;

    declare @type: ConversationServiceImpl:@Transactional;

    @Autowired
    ConversationRepository ConversationServiceImpl.conversationRepository;

    public long ConversationServiceImpl.countAllConversations() {
        return conversationRepository.count();
    }

    public void ConversationServiceImpl.deleteConversation(Conversation conversation) {
        conversationRepository.delete(conversation);
    }

    public Conversation ConversationServiceImpl.findConversation(Long id) {
        return conversationRepository.findOne(id);
    }

    public List<Conversation> ConversationServiceImpl.findAllConversations() {
        return conversationRepository.findAll();
    }

    public List<Conversation> ConversationServiceImpl.findConversationEntries(int firstResult, int maxResults) {
        return conversationRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }

    public Conversation ConversationServiceImpl.updateConversation(Conversation conversation) {
        return conversationRepository.save(conversation);
    }

}
